"""Type stubs for the quickjs._quickjs C extension."""

from typing import Any, Callable

quickjs_version: str

JS_EVAL_TYPE_GLOBAL: int
JS_EVAL_TYPE_MODULE: int
JS_EVAL_FLAG_STRICT: int
JS_EVAL_FLAG_COMPILE_ONLY: int

JS_TAG_INT: int
JS_TAG_BOOL: int
JS_TAG_NULL: int
JS_TAG_UNDEFINED: int
JS_TAG_OBJECT: int
JS_TAG_STRING: int
JS_TAG_FLOAT64: int
JS_TAG_SYMBOL: int
JS_TAG_EXCEPTION: int

class QuickJSError(Exception): ...
class JSError(QuickJSError): ...

class UndefinedType:
    def __new__(cls) -> UndefinedType: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

Undefined: UndefinedType

class Value:
    tag: int
    context: Context
    is_object: bool
    is_function: bool
    is_array: bool
    is_string: bool
    is_number: bool
    is_bool: bool
    is_null: bool
    is_undefined: bool
    is_symbol: bool
    is_error: bool
    is_constructor: bool

    def to_python(self, deep: bool = ...) -> Any: ...
    def get(self, key: str | int) -> Any: ...
    def set(self, key: str | int, value: Any) -> None: ...
    def has(self, key: str | int) -> bool: ...
    def delete(self, key: str | int) -> None: ...
    def keys(self) -> list[str]: ...
    def call(self, *args: Any, this: Any = ...) -> Any: ...
    def call_constructor(self, *args: Any) -> Any: ...
    def json(self) -> str | None: ...
    def to_bytes(self) -> bytes: ...
    def write_object(self) -> bytes: ...
    def define_property(
        self,
        key: str | int,
        value: Any = ...,
        get: Callable[..., Any] | None = ...,
        set: Callable[..., Any] | None = ...,
        writable: bool = ...,
        enumerable: bool = ...,
        configurable: bool = ...,
    ) -> None: ...
    def __call__(self, *args: Any, this: Any = ...) -> Any: ...
    def __getitem__(self, key: str | int) -> Any: ...
    def __setitem__(self, key: str | int, value: Any) -> None: ...
    def __len__(self) -> int: ...

class Context:
    runtime: Runtime
    has_pending_job: bool

    def __init__(self, runtime: Runtime | None = ...) -> None: ...
    def eval(
        self,
        code: str,
        filename: str = ...,
        module: bool = ...,
        strict: bool = ...,
        compile_only: bool = ...,
    ) -> Any: ...
    def get_global(self) -> Value: ...
    def get(self, name: str) -> Any: ...
    def set(self, name: str, value: Any) -> None: ...
    def parse_json(self, text: str, filename: str = ...) -> Any: ...
    def new_object(self) -> Value: ...
    def new_array(self) -> Value: ...
    def new_function(
        self, callable: Callable[..., Any], name: str = ..., length: int = ...
    ) -> Value: ...
    def execute_pending_job(self) -> bool: ...
    def compile(self, code: str, filename: str = ..., module: bool = ...) -> Value: ...
    def eval_function(self, value: Value) -> Any: ...
    def read_object(self, data: bytes) -> Value: ...
    def get_exception(self) -> Any: ...
    def new_array_buffer(self, data: bytes) -> Value: ...
    def new_host_object(self, obj: Any) -> Value: ...
    def set_module_loader(self, loader: Callable[[str], str | None] | None) -> None: ...
    def __enter__(self) -> Context: ...
    def __exit__(self, *exc: Any) -> bool: ...

class Runtime:
    def __init__(self) -> None: ...
    def new_context(self) -> Context: ...
    def set_memory_limit(self, limit: int) -> None: ...
    def set_max_stack_size(self, size: int) -> None: ...
    def set_gc_threshold(self, threshold: int) -> None: ...
    def run_gc(self) -> None: ...
    def set_interrupt_handler(self, handler: Callable[[], bool] | None) -> None: ...
    def compute_memory_usage(self) -> dict[str, int]: ...
    def __enter__(self) -> Runtime: ...
    def __exit__(self, *exc: Any) -> bool: ...
